# Generated by Django 3.0.6 on 2020-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('roll_no', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.TextField()),
                ('age', models.IntegerField()),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.IntegerField()),
                ('gender', models.CharField(max_length=25)),
                ('phone_no', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('mathe', models.IntegerField()),
                ('air', models.IntegerField()),
                ('total_m', models.IntegerField()),
                ('fees', models.TextField()),
                ('class_tim', models.TextField()),
                ('uni_num', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('size_avb', models.TextField()),
                ('bname', models.CharField(max_length=100)),
                ('phys', models.IntegerField()),
                ('chemis', models.IntegerField()),
                ('mmath', models.IntegerField()),
                ('block_h', models.CharField(max_length=100)),
                ('room_no', models.IntegerField()),
                ('hos_type', models.CharField(max_length=100)),
                ('distance_km', models.IntegerField()),
                ('gender_std', models.CharField(max_length=25)),
                ('can_id', models.IntegerField()),
                ('can_type', models.CharField(max_length=100)),
                ('b_timings', models.TextField()),
                ('l_timings', models.TextField()),
                ('d_timings', models.TextField()),
                ('tran_id', models.IntegerField()),
                ('tran_type', models.CharField(max_length=100)),
                ('route', models.TextField()),
                ('lib_id', models.IntegerField()),
                ('book_iss', models.TextField()),
                ('book_ret', models.TextField()),
                ('fine', models.IntegerField()),
            ],
        ),
    ]
