# Generated by Django 3.0.14 on 2021-05-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('hostel_id', models.IntegerField()),
                ('hostel_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=25)),
                ('hostel_address', models.TextField()),
            ],
        ),
    ]
