# Generated by Django 3.0.14 on 2021-05-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_hostel_owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_id', models.IntegerField()),
                ('owner_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('document', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Request_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_num', models.IntegerField()),
                ('email_std', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('document', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Request_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('teacher_subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('document', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
